export type Contractor = {
  id: string;
  name: string;
  title: string;
  country: string;
  city: string;
  timezone: string;
  skills: string[];
  yearsExperience: number;
  hourlyRate: number;
  monthlyRate: number;
  availability: "immediate" | "2weeks" | "1month";
  bio: string;
  languages: string[];
  education: string;
  previousCompanies: string[];
  interviewScore: number;
  verified: boolean;
  avatar: string;
  linkedinUrl?: string;
  portfolioUrl?: string;
  category: string;
  english: "native" | "fluent" | "professional";
};

export const CONTRACTORS: Contractor[] = [
  {
    id: "1",
    name: "Valentina Restrepo",
    title: "Senior Full-Stack Engineer",
    country: "Colombia",
    city: "Medellín",
    timezone: "UTC-5",
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS"],
    yearsExperience: 7,
    hourlyRate: 65,
    monthlyRate: 4900,
    availability: "immediate",
    bio: "Senior engineer with 7 years building SaaS products. Led engineering at two YC startups. Strong background in TypeScript, React, and distributed systems. Interviewed at Meta and Stripe.",
    languages: ["Spanish", "English"],
    education: "B.S. Computer Science, Universidad de los Andes",
    previousCompanies: ["Rappi", "Buda.com", "Hipo Technologies"],
    interviewScore: 94,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=valentina&backgroundColor=b6e3f4",
    category: "Engineering",
    english: "fluent",
  },
  {
    id: "2",
    name: "Mateo Gutiérrez",
    title: "Product Manager",
    country: "Argentina",
    city: "Buenos Aires",
    timezone: "UTC-3",
    skills: ["Product Strategy", "Roadmapping", "SQL", "Figma", "A/B Testing"],
    yearsExperience: 6,
    hourlyRate: 55,
    monthlyRate: 4100,
    availability: "2weeks",
    bio: "Product leader who shipped 3 products from 0 to 1. Background in fintech and marketplace products. Was a finalist at Uber and Mercado Libre's PM interview processes.",
    languages: ["Spanish", "English", "Portuguese"],
    education: "MBA, IAE Business School",
    previousCompanies: ["Mercado Libre", "OLX Group", "Kuda"],
    interviewScore: 91,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=mateo&backgroundColor=c0aede",
    category: "Product",
    english: "fluent",
  },
  {
    id: "3",
    name: "Camila Herrera",
    title: "UX/UI Designer",
    country: "Mexico",
    city: "Mexico City",
    timezone: "UTC-6",
    skills: ["Figma", "User Research", "Prototyping", "Design Systems", "Framer"],
    yearsExperience: 5,
    hourlyRate: 50,
    monthlyRate: 3750,
    availability: "immediate",
    bio: "Designer specializing in B2B SaaS products. Created design systems used by 50+ engineers. Finalist in Google's UX designer hiring process.",
    languages: ["Spanish", "English"],
    education: "B.A. Graphic Design, UNAM",
    previousCompanies: ["Clip", "Konfio", "Flat.mx"],
    interviewScore: 89,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=camila&backgroundColor=d1d4f9",
    category: "Design",
    english: "professional",
  },
  {
    id: "4",
    name: "Sebastián Morales",
    title: "Data Engineer",
    country: "Chile",
    city: "Santiago",
    timezone: "UTC-4",
    skills: ["Python", "dbt", "Airflow", "Spark", "BigQuery", "Snowflake"],
    yearsExperience: 8,
    hourlyRate: 70,
    monthlyRate: 4600,
    availability: "1month",
    bio: "Data engineer with deep expertise in modern data stack. Built data platforms processing 10B+ events/day. Finalist at Databricks and dbt Labs.",
    languages: ["Spanish", "English"],
    education: "M.S. Computer Science, Pontificia Universidad Católica de Chile",
    previousCompanies: ["Cornershop", "NotCo", "Falabella Tech"],
    interviewScore: 96,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sebastian&backgroundColor=b6e3f4",
    category: "Data",
    english: "fluent",
  },
  {
    id: "5",
    name: "Lucia Fernández",
    title: "Frontend Engineer",
    country: "Uruguay",
    city: "Montevideo",
    timezone: "UTC-3",
    skills: ["React", "Vue.js", "TypeScript", "CSS", "Storybook", "Playwright"],
    yearsExperience: 4,
    hourlyRate: 45,
    monthlyRate: 3400,
    availability: "immediate",
    bio: "Frontend specialist obsessed with performance and accessibility. Contributed to open-source React libraries with 5k+ GitHub stars. Finalist at Shopify.",
    languages: ["Spanish", "English"],
    education: "B.S. Systems Engineering, Universidad ORT Uruguay",
    previousCompanies: ["dLocal", "Geocom", "Scanntech"],
    interviewScore: 88,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=lucia&backgroundColor=ffd5dc",
    category: "Engineering",
    english: "professional",
  },
  {
    id: "6",
    name: "Andrés Vargas",
    title: "DevOps / Platform Engineer",
    country: "Colombia",
    city: "Bogotá",
    timezone: "UTC-5",
    skills: ["Kubernetes", "Terraform", "AWS", "GCP", "GitHub Actions", "Datadog"],
    yearsExperience: 9,
    hourlyRate: 72,
    monthlyRate: 4650,
    availability: "2weeks",
    bio: "Platform engineer who reduced infrastructure costs 40% at previous role. Deep expertise in Kubernetes and multi-cloud deployments. Finalist at HashiCorp.",
    languages: ["Spanish", "English"],
    education: "B.S. Systems Engineering, Universidad Nacional de Colombia",
    previousCompanies: ["Bancolombia Tech", "Lulo Bank", "CrediCorp"],
    interviewScore: 93,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=andres&backgroundColor=c0aede",
    category: "Engineering",
    english: "fluent",
  },
  {
    id: "7",
    name: "Isabella Santos",
    title: "Growth Marketer",
    country: "Brazil",
    city: "São Paulo",
    timezone: "UTC-3",
    skills: ["SEO", "Paid Acquisition", "Email Marketing", "Analytics", "Conversion Optimization"],
    yearsExperience: 6,
    hourlyRate: 48,
    monthlyRate: 3600,
    availability: "immediate",
    bio: "Growth marketer who scaled user acquisition from 10k to 500k MAU. Expert in SEO and performance marketing. Finalist at Duolingo and Loom.",
    languages: ["Portuguese", "English", "Spanish"],
    education: "B.A. Marketing, FGV",
    previousCompanies: ["QuintoAndar", "Creditas", "Nubank"],
    interviewScore: 87,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=isabella&backgroundColor=ffd5dc",
    category: "Marketing",
    english: "fluent",
  },
  {
    id: "8",
    name: "Carlos Mendoza",
    title: "Backend Engineer (Go/Rust)",
    country: "Peru",
    city: "Lima",
    timezone: "UTC-5",
    skills: ["Go", "Rust", "gRPC", "Kafka", "Redis", "PostgreSQL"],
    yearsExperience: 7,
    hourlyRate: 68,
    monthlyRate: 4550,
    availability: "1month",
    bio: "Systems engineer specializing in high-performance backends. Built payment processing system handling $1B+ in annual transactions. Finalist at Cloudflare.",
    languages: ["Spanish", "English"],
    education: "B.S. Computer Science, PUCP",
    previousCompanies: ["Culqi", "Banbif", "Intercorp Tech"],
    interviewScore: 95,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=carlos&backgroundColor=b6e3f4",
    category: "Engineering",
    english: "professional",
  },
  {
    id: "9",
    name: "María José López",
    title: "Head of Customer Success",
    country: "Mexico",
    city: "Guadalajara",
    timezone: "UTC-6",
    skills: ["Customer Success", "Churn Reduction", "Salesforce", "Gainsight", "SQL"],
    yearsExperience: 8,
    hourlyRate: 52,
    monthlyRate: 3900,
    availability: "immediate",
    bio: "CS leader who reduced churn from 8% to 2.1% in 18 months. Built and managed CS teams of 15+. Finalist at HubSpot and Zendesk.",
    languages: ["Spanish", "English"],
    education: "B.B.A., ITESO",
    previousCompanies: ["Conekta", "Merama", "Jüsto"],
    interviewScore: 90,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=mariajose&backgroundColor=d1d4f9",
    category: "Operations",
    english: "fluent",
  },
  {
    id: "10",
    name: "Felipe Rojas",
    title: "ML / AI Engineer",
    country: "Argentina",
    city: "Córdoba",
    timezone: "UTC-3",
    skills: ["Python", "PyTorch", "LangChain", "MLflow", "Hugging Face", "FastAPI"],
    yearsExperience: 5,
    hourlyRate: 75,
    monthlyRate: 4700,
    availability: "2weeks",
    bio: "ML engineer building production LLM applications. Fine-tuned models deployed at scale for 3M+ users. Finalist at Anthropic and Cohere.",
    languages: ["Spanish", "English"],
    education: "M.S. Data Science, Universidad de Buenos Aires",
    previousCompanies: ["Satellogic", "Etermax", "Despegar Tech"],
    interviewScore: 97,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=felipe&backgroundColor=b6e3f4",
    category: "AI/ML",
    english: "fluent",
  },
  {
    id: "11",
    name: "Sofía Ramírez",
    title: "Product Designer",
    country: "Colombia",
    city: "Cali",
    timezone: "UTC-5",
    skills: ["Figma", "Motion Design", "UX Writing", "Design Tokens", "Webflow"],
    yearsExperience: 4,
    hourlyRate: 42,
    monthlyRate: 3150,
    availability: "immediate",
    bio: "Designer who merged brand and product design into cohesive experiences. Created award-winning redesign featured in Awwwards. Finalist at Figma.",
    languages: ["Spanish", "English"],
    education: "B.A. Industrial Design, Universidad de los Andes",
    previousCompanies: ["Addi", "Frubana", "Leal"],
    interviewScore: 86,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sofia&backgroundColor=ffd5dc",
    category: "Design",
    english: "professional",
  },
  {
    id: "12",
    name: "Diego Castillo",
    title: "Engineering Manager",
    country: "Chile",
    city: "Valparaíso",
    timezone: "UTC-4",
    skills: ["Team Leadership", "System Design", "Agile", "OKRs", "Technical Hiring"],
    yearsExperience: 12,
    hourlyRate: 85,
    monthlyRate: 5000,
    availability: "1month",
    bio: "Engineering leader who scaled teams from 5 to 40 engineers. Deep IC background in distributed systems. Finalist at Scale AI and Figma.",
    languages: ["Spanish", "English"],
    education: "M.S. Computer Science, Universidad Técnica Federico Santa María",
    previousCompanies: ["Buk", "Betterfly", "Cencosud Digital"],
    interviewScore: 92,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=diego&backgroundColor=c0aede",
    category: "Engineering",
    english: "fluent",
  },
  {
    id: "13",
    name: "Ana Beatriz Costa",
    title: "Data Scientist",
    country: "Brazil",
    city: "Rio de Janeiro",
    timezone: "UTC-3",
    skills: ["Python", "R", "Statistical Modeling", "Causal Inference", "Tableau"],
    yearsExperience: 6,
    hourlyRate: 60,
    monthlyRate: 4500,
    availability: "immediate",
    bio: "Data scientist specializing in experimentation and causal inference. Designed A/B testing framework used across 200+ experiments. Finalist at Airbnb.",
    languages: ["Portuguese", "English", "Spanish"],
    education: "M.S. Statistics, IMPA",
    previousCompanies: ["iFood", "Loft", "Pismo"],
    interviewScore: 93,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=anabeatriz&backgroundColor=ffd5dc",
    category: "Data",
    english: "fluent",
  },
  {
    id: "14",
    name: "Ricardo Vega",
    title: "Sales Engineer",
    country: "Mexico",
    city: "Monterrey",
    timezone: "UTC-6",
    skills: ["Enterprise Sales", "Solution Architecture", "APIs", "Demos", "Salesforce"],
    yearsExperience: 7,
    hourlyRate: 58,
    monthlyRate: 4350,
    availability: "immediate",
    bio: "Sales engineer with $12M in closed ARR over 3 years. Bridges technical depth with buyer empathy. Finalist at Twilio and Segment.",
    languages: ["Spanish", "English"],
    education: "B.S. Information Systems, Tec de Monterrey",
    previousCompanies: ["Clip", "Kushki", "Pagando"],
    interviewScore: 89,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ricardo&backgroundColor=b6e3f4",
    category: "Sales",
    english: "native",
  },
  {
    id: "15",
    name: "Alejandra Núñez",
    title: "Backend Engineer (Python/Django)",
    country: "Ecuador",
    city: "Quito",
    timezone: "UTC-5",
    skills: ["Python", "Django", "FastAPI", "Celery", "PostgreSQL", "Redis"],
    yearsExperience: 5,
    hourlyRate: 52,
    monthlyRate: 3900,
    availability: "2weeks",
    bio: "Backend engineer who architected multi-tenant SaaS infrastructure from scratch. Passionate about clean code and DDD. Finalist at Lemon.io.",
    languages: ["Spanish", "English"],
    education: "B.S. Software Engineering, ESPE",
    previousCompanies: ["PayPhone", "TuCarrito", "Kushki"],
    interviewScore: 87,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alejandra&backgroundColor=d1d4f9",
    category: "Engineering",
    english: "professional",
  },
  {
    id: "17",
    name: "Paula Bianchi",
    title: "Executive Assistant / Virtual Assistant",
    country: "Argentina",
    city: "Buenos Aires",
    timezone: "UTC-3",
    skills: ["Calendar Management", "Travel Planning", "Notion", "Email Triage", "Bookkeeping"],
    yearsExperience: 8,
    hourlyRate: 28,
    monthlyRate: 2100,
    availability: "immediate",
    bio: "Executive assistant supporting C-suite at fast-growing startups. Manages calendars, inboxes, travel, and light bookkeeping for founders. Finalist at Athena and Magic.",
    languages: ["Spanish", "English"],
    education: "B.A. Business Administration, UADE",
    previousCompanies: ["Bridgewise", "Increase", "Pomelo"],
    interviewScore: 92,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=paula&backgroundColor=ffd5dc",
    category: "Virtual Assistant",
    english: "fluent",
  },
  {
    id: "18",
    name: "Roberto Salinas",
    title: "Senior Accountant / Bookkeeper",
    country: "Mexico",
    city: "Mérida",
    timezone: "UTC-6",
    skills: ["QuickBooks", "Xero", "Month-End Close", "Payroll", "US GAAP", "Multi-Entity"],
    yearsExperience: 10,
    hourlyRate: 38,
    monthlyRate: 2850,
    availability: "2weeks",
    bio: "Accountant with deep US GAAP experience supporting US SaaS startups remotely. Handles month-end close, AR/AP, and payroll for 8 different companies. Finalist at Pilot.com.",
    languages: ["Spanish", "English"],
    education: "B.S. Accounting, UADY; CPA-equivalent",
    previousCompanies: ["Kavak", "Konfio", "Albo"],
    interviewScore: 90,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=roberto&backgroundColor=c0aede",
    category: "Finance",
    english: "fluent",
  },
  {
    id: "19",
    name: "Daniela Pereira",
    title: "Content Writer / SEO Specialist",
    country: "Brazil",
    city: "Curitiba",
    timezone: "UTC-3",
    skills: ["Long-form Content", "SEO Copywriting", "Editorial Strategy", "Ahrefs", "Substack"],
    yearsExperience: 6,
    hourlyRate: 45,
    monthlyRate: 3400,
    availability: "immediate",
    bio: "Content writer who grew a B2B SaaS blog from 0 to 400k monthly organic visits. Native-quality English writing. Finalist at Buffer and Wistia content roles.",
    languages: ["Portuguese", "English", "Spanish"],
    education: "B.A. Journalism, UFPR",
    previousCompanies: ["RD Station", "Hotmart", "Resultados Digitais"],
    interviewScore: 91,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=daniela&backgroundColor=ffd5dc",
    category: "Content / Writing",
    english: "native",
  },
  {
    id: "20",
    name: "Javier Ortega",
    title: "SDR / Outbound Sales",
    country: "Colombia",
    city: "Medellín",
    timezone: "UTC-5",
    skills: ["Outbound Prospecting", "Apollo", "Salesloft", "Cold Email", "LinkedIn Sales Nav"],
    yearsExperience: 4,
    hourlyRate: 30,
    monthlyRate: 2250,
    availability: "immediate",
    bio: "SDR who consistently hit 150% of quota over 8 quarters. Booked $4M+ in qualified pipeline for US SaaS companies. Finalist at Outreach and Gong.",
    languages: ["Spanish", "English"],
    education: "B.A. International Business, EAFIT",
    previousCompanies: ["Truora", "Rappi B2B", "Habi"],
    interviewScore: 88,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=javier&backgroundColor=b6e3f4",
    category: "Sales",
    english: "fluent",
  },
  {
    id: "21",
    name: "Gabriela Ruiz",
    title: "Technical Recruiter",
    country: "Mexico",
    city: "Mexico City",
    timezone: "UTC-6",
    skills: ["Sourcing", "Greenhouse", "Lever", "Boolean Search", "Candidate Closing"],
    yearsExperience: 7,
    hourlyRate: 42,
    monthlyRate: 3150,
    availability: "2weeks",
    bio: "Technical recruiter who placed 90+ engineers at US Series A–C startups. Known for white-glove candidate experience. Finalist at Triplebyte.",
    languages: ["Spanish", "English"],
    education: "B.A. Psychology, UNAM",
    previousCompanies: ["Clip", "Stori", "Bitso"],
    interviewScore: 89,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=gabriela&backgroundColor=d1d4f9",
    category: "HR / Recruiting",
    english: "fluent",
  },
  {
    id: "22",
    name: "Tomás Alvarez",
    title: "iOS / Mobile Engineer",
    country: "Argentina",
    city: "Rosario",
    timezone: "UTC-3",
    skills: ["Swift", "SwiftUI", "Objective-C", "React Native", "Firebase"],
    yearsExperience: 6,
    hourlyRate: 62,
    monthlyRate: 4650,
    availability: "immediate",
    bio: "Mobile engineer who shipped apps with 1M+ downloads. Strong SwiftUI and performance optimization background. Finalist at Duolingo.",
    languages: ["Spanish", "English"],
    education: "B.S. Computer Engineering, Universidad Nacional de Rosario",
    previousCompanies: ["Naranja X", "Ualá", "Personal Pay"],
    interviewScore: 91,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tomas&backgroundColor=c0aede",
    category: "Engineering",
    english: "fluent",
  },
];

export const CATEGORIES = [
  "All",
  "Engineering",
  "Product",
  "Design",
  "Data",
  "AI/ML",
  "Marketing",
  "Sales",
  "Operations",
  "Customer Success",
  "Finance",
  "HR / Recruiting",
  "Content / Writing",
  "Virtual Assistant",
];

export const COUNTRIES = ["All", "Argentina", "Brazil", "Chile", "Colombia", "Ecuador", "Mexico", "Peru", "Uruguay"];

export const AVAILABILITY_LABELS = {
  immediate: "Available Now",
  "2weeks": "2 Weeks",
  "1month": "1 Month",
};

export function getContractor(id: string): Contractor | undefined {
  return CONTRACTORS.find((c) => c.id === id);
}

export type ContractorContact = {
  email: string;
  phone: string;
  linkedin: string;
  interviewRecordingUrl: string;
};

/**
 * Deterministic mock contact info for a contractor. In production, this
 * would come from Supabase and only be returned for authenticated paying
 * users.
 */
export function getContractorContact(c: Contractor): ContractorContact {
  const slug = c.name
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z]+/g, ".");
  return {
    email: `${slug}@hirefinalists-mail.com`,
    phone: `+1 (555) ${(parseInt(c.id, 10) * 137) % 900 + 100}-${(parseInt(c.id, 10) * 991) % 9000 + 1000}`,
    linkedin: `https://linkedin.com/in/${slug}-${c.id}`,
    interviewRecordingUrl: `https://hirefinalists.com/interviews/${c.id}`,
  };
}
